project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

files:
  - source: /locales/en.json
    translation: /locales/%locale_with_underscore%.%file_extension%
    update_option: update_as_unapproved
    skip_untranslated_strings: true
    export_only_approved: true