name: Auto Approve PR from Crowdin

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'rjcreathors' && github.event.pull_request.title == 'New Crowdin updates'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Automatically approved."